site_name: MkDocs DrawIO Demo
site_dir: site/
docs_dir: docs
site_url: https://abdulsalamk.github.io/mkdocs/
repo_url: https://github.com/abdulsalamk/mkdocs
edit_uri: edit/main/docs/
use_directory_urls: true

nav:
  - Home: index.md

plugins:
  - search
  - drawio

extra_css:
  - css/drawio-fix.css