site_name: MkDocs DrawIO Demo
site_dir: site/
site_url: https://abdulsalamk.github.io/mkdocs/
repo_url: https://github.com/abdulsalamk/mkdocs
edit_uri: edit/main/docs/

plugins:
  - drawio-exporter:
      format: svg  # or png
      cache_dir: 'drawio-exporter'
      edit: true
      toolbar:
        show_title: true
extra_css:
  - css/drawio-fix.css